### ISSUE TITLE
Search Bar for Vocab Entries

### ISSUE THREAD

**Issue by justinglotz** [justinglotz/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#9]
Users can search through their vocab entries and only show certain ones

-Add search bar at top of the page
- Use search function from almost amazon, searching for matches in title and description
- Re render those matches to the DOM on keyup OR enter key

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a search bar to the HTML structure and updated the main.js file to implement the search functionality for vocab entries. The search function matches title and description, and results are re-rendered on keyup or enter key press.

You can review changes in this commit: https://github.com/lkilu6456546/justinglotz-INDIVIDUAL-ASSESSMENT-vocab-YOU-lary-9/commit/898d2cc20ed18a06043c843629557a7c5f8db126.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
